/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.freeze_dolphin.debate_judge;

import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

import java.util.Objects;

public class App {

    public static void main(String[] args) {
        MainForm frame = new MainForm();
        frame.setVisible(true);
    }

}
